# SPDX-FileCopyrightText: 2021 Michel Oosterhof <michel@oosterhof.net>
#
# SPDX-License-Identifier: BSD-3-Clause

---
extends:
    default

rules:
    line-length: disable

ignore: |
    .direnv
    .tox
