# SPDX-FileCopyrightText: 2018 Florian Pelgrim
# SPDX-FileCopyrightText: 2018 Michel Oosterhof <michel@oosterhof.net>
#
# SPDX-License-Identifier: BSD-3-Clause

if $programname == 'cowrie' then action(type="omfile" file="/var/log/cowrie/cowrie.log" dirOwner="cowrie" dirGroup="cowrie" fileOwner="cowrie" fileGroup="cowrie")