# SPDX-FileCopyrightText: 2023 Michel Oosterhof <michel@oosterhof.net>
#
# SPDX-License-Identifier: BSD-3-Clause

---
blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://www.cowrie.org/slack
    about: If you have a question, or are looking for advice, please join our Slack
